global return_value
return_value = 0

NUM_BLOCKS_INDEX = 1
NUM_INODES_INDEX = 2
BLOCK_SIZE_INDEX = 3
INODE_SIZE_INDEX = 4
BLOCKS_PER_GROUP_INDEX = 5
INODES_PER_GROUP_INDEX = 6
FIRST_INODE_INDEX = 7

GROUP_NUMBER_INDEX = 1
GROUP_NUM_BLOCKS_INDEX = 2
GROUP_NUM_INODES_INDEX = 3
GROUP_NUM_FREE_BLOCKS_INDEX = 4
GROUP_NUM_FREE_INODES_INDEX = 5
GROUP_FREE_BLOCK_BITMAP_INDEX = 6
GROUP_FREE_INODE_BITMAP_INDEX = 7
GROUP_FIRST_INODE_INDEX = 8

INODE_SELF_INDEX = 1
INODE_FILE_TYPE = 2
INODE_MODE_INDEX = 3
INODE_OWNER_INDEX = 4
INODE_GROUP_INDEX = 5
INODE_LINK_COUNT_INDEX = 6
INODE_FILE_SIZE_INDEX = 10
INODE_NUM_BLOCKS_INDEX = 11

INDIRECT_PARENT_INODE_INDEX = 1
INDIRECT_DEPTH_INDEX = 2
INDIRECT_OFFSET_INDEX = 3
INDIRECT_BLOCK_INDEX = 5

DIRENT_PARENT_INDEX = 1
DIRENT_SELF_INDEX = 3
DIRENT_NAME_INDEX = 6

FREE_BLOCK_INDEX = 1
FREE_INODE_INDEX = 1
FIRST_BLOCK = 12
LAST_DIRECT_BLOCK = 23
LAST_BLOCK = 26

VALID = 0
RESERVED = 1
FREE = 2
ROOT = 2
CHILD = 0
NAME = 1
DIRECTORY = "d"
FILE = "f"
UNKNOWN_TYPE = "?"
SIZE_OF_INDIRECT_ENTRY = 4

entry_types = ["SUPERBLOCK", "GROUP", "INODE", "DIRENT", "INDIRECT", "BFREE", "IFREE"]
