all: lab3b

clean:
	rm -rf lab3b lab3b-304965058.tar.gz

dist: lab3b
	tar -czvf lab3b-304965058.tar.gz lab3b.py README Makefile Inode.py Block.py functions.py constants.py

lab3b:
	ln -s lab3b.py lab3b

